### ISSUE TITLE
[#0001] Setup inicial

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#1]

**Comment by MariaGabrielaReis** [comment]
## Setup do projeto (mobile)
Foi usado o Expo para criação do projeto. Nesta task configurei o TypeScript, ESLint e a estrutura inicial do projeto, que teve o seguinte resultado:

![estrutura do projeto](https://user-images.githubusercontent.com/69374340/225165573-e07f77be-dc3b-4052-9c57-4249e7cac8bb.png)

### Estrutura de pastas:
> 📁 **assets** - imagens, ícones e splash screen
> 📁 **src** - código fonte
> --- 📁 **components** - componentes customizados
> ----- 📰 **index.tsx** - arquivo que centraliza as importações dos componentes
> --- 📁 **screens** - telas do aplicativo
> --- 📁 **utils** - funções utilitárias


### Bibliotecas instaladas: 

```json
"@expo-google-fonts/inter": "^0.2.3"
"expo-font": "~11.1.1"
"react-native-svg": "13.4.0"
"styled-components": "^5.3.9"

 /** Dependências de desenvolvimento */
"@types/styled-components": "^5.1.26"
"@types/styled-components-react-native": "^5.2.1"
"babel-plugin-module-resolver": "^5.0.0"
"eslint": "^8.36.0"
```
