### ISSUE TITLE
[#0603] Cadastro de reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#12]
## Descrição da atividade

- Desenvolver interface para cadastro de reunião conforme o [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para cadastro de reuniões.

## Informações para execução da atividade

- ~~Somente usuários administradores podem cadastrar uma reunião.~~
- As informações que devem ser armaazenadas são as seguintes: Parceria em questão (obrigatório), data (obrigatório), hora (obrigatório) e tema (opcional).

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi usado a classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para criar uma reunião. Esse post foi feito consumindo a rota do backend através dessa função.

Tecnologias: React Native, Expo, Axios, Styled Components

Requisição
```ts
async createMeeting(meeting: IMeeting) {
    try {
      await api.post(MEETING_ENDPOINTS.CREATE, meeting);
    } catch (error) {
      console.error(error);
    }
  }
```
