### ISSUE TITLE
[#0605] Atualização de reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#13]
## Descrição da atividade

- Desenvolver interface para atualização de reunião conforme o [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para atualização de reuniões.

## Informações para execução da atividade

- ~~Somente usuários administradores podem atualizar uma reunião.~~
- As informações que podem ser atualizadas são as mesmas informadas no cadastro.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi usado a classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para editar uma reunião. Esse put foi feito consumindo a rota do backend através dessa função.

Tecnologias: React Native, Expo, Axios, Styled Components

Requisição
```ts
async updateMeeting(updatedMeeting: IMeeting) {
    try {
      const { data } = await api.put(MEETING_ENDPOINTS.EDIT, updatedMeeting);
      return data;
    } catch (error) {
      alertError(error, "Não foi possível atualizar os dados da reunião :(");
    }
  }
```

**Comment by MariaGabrielaReis** [comment]
**BLOQUEADA POR MOTIVOS DE**: está tudo ok com a task, já foi finalizada/integrada, porém o backend está mandando a response num formato que não é o que eu preciso. antes de fazer o PR dessa task preciso que a response seja padronizada e então gravo a demo da task e abro PR
