### ISSUE TITLE
[#0607] Listagem de reuniões na homepage

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#14]
## Descrição da atividade

- Criar interface para listagem de reuniões, conforme [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para listagem de reuniões.

## Informações para execução da atividade

- Qualquer usuário pode acessar a lista de reunião.
- Deve ser separado entre reuniões passadas e reuniões futuras.
- Deve ter um botão de ver mais para exibir mais reuniões.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by JoaoM-py** [comment]
<h1>Documentação</h1>

Listagem de reuniões no Homepage e nos detalhes da reunião  #14
----------------------------

- Usuários desativados não podem editar a reunião.
- Se não há reunião ele retorna uma mensagem.
- 

![ativa](https://user-images.githubusercontent.com/80930525/233513689-18913010-d472-45c9-808a-d0320f497807.jpeg)
![desaativa](https://user-images.githubusercontent.com/80930525/233513697-933e8f1d-fb9f-4862-8be0-dc1403ea0c2f.jpeg)
