### ISSUE TITLE
[#0609] Detalhes da reunião

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#15]
## Descrição da atividade

- Criar interface para ver detalhes de uma reunião específica, conforme [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para obter informações de uma reunião específica.

## Informações para execução da atividade

- Qualquer usuário pode acessar os detalhes da reunião.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaGReis** [comment]
## Documentação

Foi criado uma classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para pegar os dados de uma reunião. Esse get foi feito consumindo a rota do backend através dessa função e, ao enviar o id, foi mostrado na tela os dados da reunião.

Tecnologias: React Native, Expo, Axios, Styled Components

![Image](https://user-images.githubusercontent.com/121828257/233501651-30c39c05-73f6-4ef3-9bea-5e25af4a3176.png)

Requisição
```ts
 async getMeeting(id: string) {
    try {
      const { data } = await api.get(MEETING_ENDPOINTS.DETAILS + id);
      return data;
    } catch (error) {
      alertError(error, "Não foi possível carregar os dados da reunião :(");
    }
}
```

**Comment by ThHenrique** [comment]
pq blocked ?

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi criado uma classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para pegar os dados de uma reunião. Esse get foi feito consumindo a rota do backend através dessa função e, ao enviar o id, foi mostrado na tela os dados da reunião.

Tecnologias: React Native, Expo, Axios, Styled Components

https://user-images.githubusercontent.com/69374340/233798013-6d29fc2a-7cfe-4824-803e-4a9d57f0a4ee.mp4

![Image](https://user-images.githubusercontent.com/121828257/233501651-30c39c05-73f6-4ef3-9bea-5e25af4a3176.png)

Requisição
```ts
 async getMeeting(id: string) {
    try {
      const { data } = await api.get(MEETING_ENDPOINTS.DETAILS + id);
      return data;
    } catch (error) {
      alertError(error, "Não foi possível carregar os dados da reunião :(");
    }
}
```
