### ISSUE TITLE
[#0611] Exclusão de reunião

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#16]
## Descrição da atividade

- Certificar-se de que a exclusão da reunião acontece de acordo com [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para exclusão de reunião.

## Informações para execução da atividade

- ~~Somente o usuário administrador pode excluir uma reunião.~~

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi usado a classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para excluir uma reunião. Esse delete foi feito consumindo a rota do backend através dessa função.

Tecnologias: React Native, Expo, Axios, Styled Components

Requisição
```ts
async deleteMeeting(id: string) {
    try {
      await api.delete(MEETING_ENDPOINTS.DELETE + id);
      Alert.alert(
        "Reunião excluída!",
        "Esta reunião deixará de aparecer em listagens e históricos",
      );
    } catch (error) {
      alertError(error, "Não foi possível deletar a reunião :(");
    }
  }
```

**Comment by MariaGabrielaReis** [comment]
**BLOQUEADA POR MOTIVOS DE:** está tudo ok com a task, já foi finalizada, só falta o PR, mas só tem 2 reuniões e se eu excluir elas pra gravar a demo da tarefa vai ficar sem reunião pra testar outras tasks, então vou fazer e abrir PR da task de **CADASTRO DE REUNIÃO** antes de fechar essa, aí n vai ter problema deletar outras reuniões.
