### ISSUE TITLE
[#0702] Cadastro de anotações em reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#17]
## Descrição da atividade

- Desenvolver interface para cadastro de anotações de reunião conforme o [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para cadastro de reuniões.

## Informações para execução da atividade

- ~~Somente usuários administradores podem cadastrar uma anotação.~~
- As informações que devem ser armazenadas são as seguintes: Data de atualização (automática), reunião em questão, dono do comentário e o comentário em si.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by drisabelles** [comment]
@MariaGabrielaReis informações para execução da atividade atualizada

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi usado a classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para criar uma anotação de uma reunião. Esse post foi feito consumindo a rota do backend através dessa função.

Tecnologias: React Native, Expo, Axios, Styled Components

Requisição
```ts
async createMeetingComment(meetingId: string, comment: string) {
    try {
      const { data } = await api.post(
        MEETING_ENDPOINTS.ADD_COMMENT + meetingId,
        comment,
      );
      return data;
    } catch (error) {
      alertError(error, "Não foi possível cadastrar o comentário :(");
    }
  }
```
