### ISSUE TITLE
[#0704] Edição de anotações em reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#18]
## Descrição da atividade

- Criar interface para edição de anotações em reuniões, conforme [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para edição de anotações em reuniões.

## Informações para execução da atividade

- Somente o usuário que criou a anotação pode editar uma anotação, se ele ainda for administrador.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi usado a classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para editar uma anotação de uma reunião. Esse put foi feito consumindo a rota do backend através dessa função.

Tecnologias: React Native, Expo, Axios, Styled Components

Requisição
```ts
async updateMeetingComment(comment: IComment) {
    try {
      const { data } = await api.put(
        MEETING_ENDPOINTS.UPDATE_COMMENT + comment.id,
        comment,
      );
      return data;
    } catch (error) {
      alertError(error, "Não foi possível atualizar o comentário :(");
    }
  }
```
