### ISSUE TITLE
[#0706] Listagem de anotações de reuniões

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#19]
## Descrição da atividade

- Criar interface para listagem de anotações de reuniões, conforme [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para listagem de anotações de reuniões.

## Informações para execução da atividade

- Qualquer usuário pode acessar a lista de anotações de reunião.

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Code review
- [x] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi usado a classe para agrupar as requisições que envolvem as reuniões, onde existe uma função para listar as anotações de uma reunião. Esse get foi feito consumindo a rota do backend através dessa função e, ao enviar o id da reunião, foi mostrado na tela todas as anotações existentes.

Tecnologias: React Native, Expo, Axios, Styled Components

Requisição
```ts
async getMeetingComments(id: string) {
    try {
      const { data } = await api.get(MEETING_ENDPOINTS.COMMENTS + id);
      return data;
    } catch (error) {
      alertError(
        error,
        "Não foi possível carregar os comentários da reunião :(",
      );
    }
  }
```
