### ISSUE TITLE
[#0109] Edição de parcerias

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#3]
## Descrição da atividade

- Criar interface para edição de parcerias de acordo com [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11%3A195&t=PGBtovxk0Gj4sXR2-0);
- Consumir rota criada pelo back para edição de parcerias.

## Informações para execução da atividade

Todas as informações informadas durante o cadastro de parcerias podem ser editadas.

## DoR

- [x] Prototipado
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by JoaoM-py** [comment]
> @JoaoM-py falta o que para concluir essa task? precisa de alguma informação para levar ela adiante?

Resolver alguns problemas com o tipo. Na tentativa de fazer o input aceitar number agora está trazendo como undefined.  Vou procurar sobre e tentar resolver isso hoje.
