### ISSUE TITLE
[#0110] Buscar parceria pelo nome

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#32]
## Descrição da atividade

Na tela de listagem de parcerias, deve ser possível buscar uma parceria pelo seu nome.

Seguir protótipo:

![image](https://user-images.githubusercontent.com/78885451/229578117-66d5058e-d4d1-4e1e-b50b-c65512d296be.png)

## Informações para execução da atividade

- Qualquer usuário pode realizar a busca pelo nome da parceria.
- Podem ser buscadas parcerias ativas e parcerias deletadas, porém cada uma em sua respectiva aba.
- Caso a parceria não seja encontrada, aparecer a mensagem de "nenhuma parceria encontrada".

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [ ] Code review
- [ ] Testado e integrado
- [x] Documentado
- [ ] Aceito pelo PO

**Comment by drisabelles** [comment]
@gioliveirass só precisa descrever a task e renomear se achar necessário

**Comment by gioliveirass** [comment]
@drisabelles task atualizada ✔️ qualquer dúvida pode me acionar

**Comment by drisabelles** [comment]
Blocked devido a refatorar antes de iniciar essa task

**Comment by drisabelles** [comment]
## Documentação

Criação da barra de busca com a filtragem das parcerias.

Tecnologias: React Native, Expo, Axios, Styled Components

https://user-images.githubusercontent.com/79321198/233813710-0aee4ce6-08c0-4125-ab2f-3ce2b09f008c.mp4

Requisição para listar as parcerias por nome:
```ts
 async getPartnershipByName(name: string) {
    try {
      const { data } = await api.get(
        PARTNERSHIP_ENDPOINTS.LIST_BY_NAME + `?name=${name}`,
      );
      return data;
    } catch (error) {
      alertError(error, "Não foi possível filtrar as parcerias");
    }
  }
```
