### ISSUE TITLE
[#0007] Refatoração do front-end

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#33]

**Comment by gioliveirass** [comment]
Anotação da retro: utilizar essa task inclusive para aplicar um padrão de projeto no front-end até o fim da semana

**Comment by MariaGabrielaReis** [comment]
- [ ] Colocar Controllers de requisição do handlers para services
- [ ] Tratar erros (não só console.error no terminal)
- [ ] Try catch no service (authenticate)
- [ ] Passar endpoints pra constants
- [ ] Padronizar requisições com "verbo" + "entidade" (como "getPartnerships")
- [ ] Tirar utils de fora (usar só shared/utils)
- [ ] Colocar os modais das telas acoplados nas pastas onde são usados
- [ ] Remover react-hook-form (usar refs no lugar)
- [ ] Tirar o R dos "handler"
- [ ] Ver padrões pro text
- [ ] Separar componentes de history e meetinglist
- [ ] Tirar bottom tabs da tela de parceria (colocar botão de boltar)
- [ ] Refactor no input
- [ ] Callback no modal quando fechar atualizar a tela de trás
- [ ] Ajustar os imports relativos

**Comment by gioliveirass** [comment]
@ThHenrique @MariaGabrielaReis @JoaoM-py vcs conseguiram tratar o status?

**Comment by gioliveirass** [comment]
beleza

**Comment by drisabelles** [comment]
O card será movido para done, uma vez que as alterações já foram mergeadas e as atividades referentes a ele que não foram realizadas serão criados cards a parte.
