### ISSUE TITLE
[#0111] Ajustar tela de parcerias deletadas

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#35]
## 📄 Descrição da atividade

A tela de parcerias deletadas não está de acordo com o protótipo e precisa ser ajustada.

## 🛠 Protótipo

![image](https://user-images.githubusercontent.com/78885451/229806700-efe46f5e-5760-46c9-affa-0c6b62158440.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Deve exibir as informações da parceria
- [x] Não deve permitir adicionar ou atualizar informações

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [x] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by JoaoM-py** [comment]
<h1>Documentação</h1>


Atualizar tela de parceria deletadas conforme o protótipo #35
---------
 
-Botões de edição e exclusão omitidos, junto da edição de comentários 
 
![WhatsApp Image 2023-04-11 at 5 22 05 PM](https://user-images.githubusercontent.com/80930525/231280091-bda743e3-bf35-49d7-b08c-ccd5c3aa6427.jpeg)
![WhatsApp Image 2023-04-11 at 5 22 04 PM](https://user-images.githubusercontent.com/80930525/231280103-bc0155a9-d91b-42b1-a264-225a213490f3.jpeg)

**Comment by gioliveirass** [comment]
@JoaoM-py @drisabelles mto bomm
