### ISSUE TITLE
[#0008] Adicionar botão de voltar nas páginas necessárias

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#37]
## 📄 Descrição da atividade

Adicionar botao com icone de voltar nas paginas necessarias

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Em desenvolvimento...

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by gioliveirass** [comment]
@ThHenrique cade a documentação? Tem o link, por favor?

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias
React Native, Expo, React Navigation, VSCODE

## Descrição
Adicionar botão de voltar na página de parceiria

## Issues Relacionada
#37 

## Lista de Mudanças

- Criação do componente com o ícone de voltar (arrow-left);
- Configuração dos grupos na StackNavigation que irão precisar mostrar o ícone de voltar ou nãoç
- Adição do ícone de voltar

---

## Comentários Adicionais

As "Screens" que precisam do ícone de voltar devem ser adicionas no grupo da Stack com a configuração alterada. "HeaderShown = true".

```typescript 
<Stack.Navigator initialRouteName="SignIn">
        <Stack.Group screenOptions={{ headerShown: false }}>
          <Stack.Screen name="SignIn" component={SignIn} />
          <Stack.Screen name="HomeStack" component={BottomTabs} />
        </Stack.Group>
        <Stack.Group
          screenOptions={{
            headerTitle: "",
            headerBackTitle: "",
            headerShown: true,
            headerTransparent: true,
            headerBackVisible: false,
            headerLeft: () => <CustomHeaderTitle />,
          }}
        >
           {/* ADICIONE AQUIIIIIIIIIIIIIIII> */}
          <Stack.Screen name="Partnership" component={Partnership} />
        </Stack.Group>
```

## Checklist
- [x] O código foi testado e está funcionando corretamente
- [x] As mudanças foram revisadas por um colega de equipe
- [ ] A documentação foi atualizada, se necessário
- [ ] A issue relacionada foi atualizada, se existir

**Comment by ThHenrique** [comment]
@gioliveirass doc anexada
