### ISSUE TITLE
[#0009] Trocar dropdown por select

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#38]
## 📄 Descrição da atividade

Trocar dropdown por select.

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points

### Critérios de aceite

- [x] Alterar dropdawns das telas de cadastro e edição de parcerias por um select

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by JoaoM-py** [comment]
<h1>Trocando Dropdown por select</h1> #42 

- Foi feita a troca pela lib react-native-picker nas tela de criação e edição 


https://user-images.githubusercontent.com/80930525/231277684-b36af1bf-54bf-4e0a-bf1f-12942d551df7.mp4




https://user-images.githubusercontent.com/80930525/231277847-3f5c9b7f-ef22-4fd2-afff-5b30a5bff498.mp4

**Comment by gioliveirass** [comment]
@JoaoM-py @drisabelles  ficou otimo
