### ISSUE TITLE
[#0010] Testar e validar funcionalidades já desenvolvidas

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#39]
## 📄 Descrição da atividade

Testar e validar funcionalidades já desenvolvidas, com o objetivo de identificar e corrigir bugs.

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points

### Critérios de aceite

- [ ] Identificar e reportar os problemas para que os mesmos possam ser corrigidos o quanto antes

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [ ] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by ThHenrique** [comment]
Eai galera, feedbacks @GabrielCamargoL @MariaGabrielaReis  @gioliveirass @JoaoM-py  @drisabelles
