### ISSUE TITLE
[#0104] Listar parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#4]
## Descrição da atividade

- Criar interface para listagem de parcerias de acordo com [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11%3A195&t=PGBtovxk0Gj4sXR2-0);
- Consumir rota criada pelo back para listagem de parcerias.

## DoR

- [x] Prototipado
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by drisabelles** [comment]
by @JoaoM-py no PR https://github.com/The-Bugger-Ducks/owl-partners-mobile/pull/22

Listagem de parceiro https://github.com/The-Bugger-Ducks/owl-partners-mobile/issues/4
Fetch direto da API:

![Image](https://user-images.githubusercontent.com/79321198/229389033-fe611371-4169-4b01-9692-09d05a9e6817.png)

Listagem:

![Image](https://user-images.githubusercontent.com/79321198/229389092-ef21c44b-60c5-4ac6-913f-030a70f7dd70.png)

Esta funcionando, por conta do meu celular não ter voltado a vida direito não consigo mostrar o resultado com prints, mas antes de morrer eu testei e deu certo(confia).

Obs: Ignorar por enquanto as mudanças da pasta partnershipEdit, esse PR é apenas para as mudanças do createPartnership

**Comment by gioliveirass** [comment]
Não foi feita a separação de parcerias ativas e deletadas prototipada?

**Comment by MariaGabrielaReis** [comment]
@gioliveirass https://github.com/The-Bugger-Ducks/owl-partners-mobile/pull/30

Agora está em PR
