### ISSUE TITLE
[#0612] Listagem de reuniões na tela de detalhes da parceria

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#40]
## 📄 Descrição da atividade

Na aba "Reuniões" da tela de parcerias deve ser exibida a listagem de reuniões da parceria ordenada pela data mais recente para mais antiga.

## 🛠 Protótipo

![Image](https://user-images.githubusercontent.com/78885451/230447068-c9d2f115-6b4a-446d-9f6d-c223c8807438.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [ ] Deve listar todas as reuniões da parceria em específico
- [ ] Deve ordenar da data mais recente para mais antiga
- [ ] Ao clicar em um reunião, deve abrir a página de detalhes dela
- [ ] Deve estar divididas entre "reuniões passadas" e "reuniões futuras"

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by gioliveirass** [comment]
@JoaoM-py protótipo atualizado de acordo com o que conversamos na terça dia 04/04

**Comment by JoaoM-py** [comment]
<h1>Documentação</h1>

<h2>Listagem de reunião nos detalhes da parceria</h2>


- Usuários desativados não podem editar a reunião.
- Se não há reunião ele retorna uma mensagem.

![ativa](https://user-images.githubusercontent.com/80930525/233513689-18913010-d472-45c9-808a-d0320f497807.jpeg)
![desaativa](https://user-images.githubusercontent.com/80930525/233513697-933e8f1d-fb9f-4862-8be0-dc1403ea0c2f.jpeg)
