### ISSUE TITLE
[#0012] Tratamento dos status das parcerias

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#48]
Os status devem aparecer de forma amigável para o utilizador, por exemplo: ao invés de exibir "EmProspeccao" deve exibir "Em prospecção". Isso deve ocorrer em qualquer lugar que os status apareçam na aplicação, como na tela de cadastro de parcerias e no detalhe de parcerias.

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias
React Native, Expo, VSCODE

## Descrição
Tratando os status das parceirias que estavam sendo mostrado com o valor do Enum. Agora para o usuário, fica disponível o status com o valor normal

## Issues Relacionada
#48 

## Lista de Mudanças

- Criação dos 4 métodos abaixo

1. formatPartnerStatusByList - Formata o status das parcerias em lista
2. formatStatus - Formata o status de uma parceiria
3. getPartnerStatusEnumByKey - Pega o status enum pelo chave do status
4. getPartnerStatusEnumByValue - Pega o status enum pelo valor do status


---

## Comentários Adicionais

Na página de edição de parceiria, como o status foi formatado, para pegar o valor inicial do status de acordo com o que vem da props, foi necessário fazer o get do enum e passar a chave para o formulário.

```typescript 
const partnerStatus =
        getPartnerStatusEnumByValue(partnerProps["status"])?.statusKey ??
        partnerProps["status"];
      setValue("status", partnerStatus);
```

## Checklist
- [x] O código foi testado e está funcionando corretamente
- [ ] As mudanças foram revisadas por um colega de equipe
- [ ] A documentação foi atualizada, se necessário
- [ ] A issue relacionada foi atualizada, se existir
