### ISSUE TITLE
[#0301] Adicionar comentários de atualização em uma parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#5]
## Descrição da atividade

- Criar interface para adição de comentários de atualizações em parcerias de acordo com [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11%3A195&t=PGBtovxk0Gj4sXR2-0);
- Consumir rota criada pelo back para adição de comentários de atualizações em parcerias.

## Informações para execução da atividade

Os comentários devem possuir as seguintes informações:
- Tipo de comentário (na tela da parceria, só será possível adicionar comentários do tipo atualização);
- Última atualização (ordenar pela atualização mais recente);
- O comentário em si.

Somente o usuário administrador pode inserir comentários, mas todos no sistema podem ler.
Somente o dono do comentário pode editar o comentário.

## DoR

- [x] Prototipado
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
const [tab, setTab] = useState(0);
  const [annotations, setAnnotations] = useState<IComment[]>();
  // const navigation = useNavigation();

  async function getData() {
    const comments = await AnnotationController.getAnnotations(
      "d65d3f16-ead4-4b4b-a3ce-84b9ddf20a51",
    );
    setAnnotations(comments);
  }

  useEffect(() => {
    getData();
  }, []);

  async function handleDeletePartnership() {
    // await PartnershipController.deletePartnership("123");
    // navigation.navigate("Partnerships");
  }



 async createAnnotation(partnerId: string, comment: string) {
    try {
      const user = await StorageController.getUserInfo();
      await api.post(ANNOTATION_ENDPOINTS.CREATE, {
        partnerId,
        comment,
        userId: user?.id,
      });
    } catch (error) {
      console.error(error);
    }
  }



function History({ data }: HistoryProps) {
  const [newComment, setNewComment] = useState("");

  async function handleAddComment() {
    await AnnotationController.createAnnotation(
      "d65d3f16-ead4-4b4b-a3ce-84b9ddf20a51",
      newComment,
    );

    data = await AnnotationController.getAnnotations(
      "d65d3f16-ead4-4b4b-a3ce-84b9ddf20a51",
    );
  }

  return (
    <>
      <Input
        label={"Inserir atualização"}
        placeholder={"Nova atualização sobre a parceria..."}
        onChangeText={text => setNewComment(text)}
        hasOutIcon
        onPressIcon={handleAddComment}
      />

      <Text size={14} color={"#666666"} style={{ marginVertical: 16 }}>
        Todas as atualizações e anotações
      </Text>

      {data?.map(card => {
        return (
          <Card
            key={card.id}
            id={card.id}
            type={card.title ? "annotation" : "update"}
            date={formatDate(card.createdAt)}
            time={formatTime(card.createdAt)}
            description={card.comment}
            author={card.userName}
            title={card.title}
          />
        );
      })}
    </>
  );
}
