### ISSUE TITLE
[#0015] Remover react-hook-form

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#60]

**Comment by MariaGabrielaReis** [comment]
## Documentação

Remoção do uso do React Hook Form nos modais de criação e edição de parcerias.

Tecnologias: React Native, Expo, Axios, Styled Components

| Antes                | Depois             |
| :---------------: | :---------------: |
| ![image](https://user-images.githubusercontent.com/69374340/234321889-c7452961-7db4-4934-8ecf-c91a2f22f63a.png) | ![image](https://user-images.githubusercontent.com/69374340/234322205-fe308824-b0b0-4e07-aecb-4720e3018426.png) |
