### ISSUE TITLE
[#0405] Cadastrar usuários

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#65]
## 📄 Descrição da atividade

Criar tela e consumir rota para cadastro de usuários.

Os dados necessários para cadastrar um usuário são os seguintes:

• Nome (obrigatório);
• E-mail (obrigatório);
• Senha (obrigatório);
• Nível de privilégio (obrigatório) - o usuário não seleciona, por padrão essa opção é sempre usuário simples.

## 🛠 Protótipo

Inserção de botão na tela de login que deve levar até a tela de cadastro:

![Image](https://github.com/The-Bugger-Ducks/owl-partners-mobile/assets/78885451/9a72b53a-a0c7-4f58-b43b-10e11b5bdafa)

Tela de cadastro de usuários (o botão "Cadastrar usuário" fica disabled até que todas as informações sejam inseridas).

![Image](https://github.com/The-Bugger-Ducks/owl-partners-mobile/assets/78885451/0a8c655d-1cab-4211-838a-263dd4ba890d)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [ ] Criar botão para acessar dashboard
- [ ] Criar tela de cadastro de usuários
- [ ] Consumir rota para cadastro de usuários

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [ ] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by drisabelles** [comment]
@gioliveirass o usuário poderá se cadastrar no aplicativo ou somente poderá ser cadastrado pelo administrador?

**Comment by gioliveirass** [comment]
@drisabelles o usuário pode se cadastrar como usuário simples somente. Os usuários administradores podem promover outros usuários a administradores em outra tela. 

@JoaoM-py protótipo concluído.
