### ISSUE TITLE
[#0304] Editar comentários de atualização em uma parceria

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#7]
## Descrição da atividade

- Criar interface para edição de comentários de atualizações em parcerias de acordo com [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11%3A195&t=PGBtovxk0Gj4sXR2-0);
- Consumir rota criada pelo back para edição de comentários de atualizações em parcerias.

## Informações para execução da atividade

Deve ser possível atualizar:
- Última atualização passa a ser a data e hora da atualização;
- O comentário em si.

Somente o dono do comentário pode realizar a edição, se ele ainda for administrador do sistema.

## DoR

- [x] Prototipado
- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
# Documentação

Foi utilizado a classe criada para agrupar as requisições que envolvem as anotações de parceria (AnnotationsController), onde existe uma função para atualização de anotações. Esse update foi feito consumindo a rota do backend através dessa função e, ao captar o comentário atualizado por um input num modal do aplicativo, foi enviado ao servidor e recarregado a listagem.


**Tecnologias:** React Native, Expo, Axios, Styled Components

https://user-images.githubusercontent.com/69374340/229381479-cf7e5d50-dc15-4cd8-bc40-4c92a5f58f69.mp4

### Requisição
```ts
 async updateAnnotation(
    commentId: string,
    partnerId: string,
    comment: string,
  ) {
    try {
      const { data } = await api.put(ANNOTATION_ENDPOINTS.EDIT + commentId, {
        partnerId,
        comment,
      });
      return data;
    } catch (error) {
      console.error(error);
    }
  }
```

### Modal para edição do comentário
```ts
 <Modal
        visible={isEditCommentModalOpen}
        onClose={() => setIsEditCommentModalOpen(false)}
        title={"Editar comentário"}
        buttonTitle="Editar comentário"
        onPressButton={handleEditComment}
        isLoading={isLoading}
        content={
          <Input
            value={editedComment}
            onChangeText={text => setEditedComment(text)}
          />
        }
  />
```

### Função que atualiza o comentário e a listagem
```ts
 async function handleEditComment() {
    setIsLoading(true);
    await AnnotationController.updateAnnotation(
      modalComment?.id ?? "",
      "baadc558-2791-4f9a-8d1e-e01a0a92b432", // id fixo para entrega da tarefa
      editedComment,
    );
    const updatedComments = await AnnotationController.getAnnotations(
      "baadc558-2791-4f9a-8d1e-e01a0a92b432", // id fixo para entrega da tarefa
    );
    updatedComments && setAnnotations(updatedComments);
    setEditedComment("");
    setIsLoading(false);
    setIsEditCommentModalOpen(false);
  }
```
