### ISSUE TITLE
[#0021] Reuniões de parcerias deletadas

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-mobile#72]
## 📄 Descrição da atividade

Em uma parceria deletada, deve somente exibir a lista de todas as reuniões que ocorreram (equivalente a Últimas Reuniões na parceria ativa).

~~Não deve ser possível acessar os detalhes dessas reuniões.~~
As reuniões antigas que estão listada  podem ter seus detalhes acessados, mas não é possível modificar informações nem modificar/adicionar comentários.

## 🛠 Protótipo

![Image](https://user-images.githubusercontent.com/78885451/236333965-13ead9e3-5087-46ae-a246-b6145d2ba156.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Deve ser possível vizualizar uma lista de reuniões ocorridas (Últimas reuniões);
- [ ] Deve ser possível visualizar uma reunião listada;
- [ ] Não deve ser possível modificar detalhes das reuniões;
- [ ] Não deve ser possível modificar comentários das reuniões;
- [ ] Não deve ser possível adicionar comentários nas reuniões;
- [x] As reuniões que estariam marcadas para datas após a inativação devem ser excluídas.

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [ ] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by gioliveirass** [comment]
Em validação.

**Comment by gioliveirass** [comment]
Validado.

**Comment by drisabelles** [comment]
@gioliveirass e o que acontece com uma reunião que estava marcada para uma data depois do dia no qual a parceria foi desativada?

**Comment by gioliveirass** [comment]
Pode ser excluída.
