### ISSUE TITLE
[#0108] Excluir parcerias

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-mobile#8]
## Descrição da atividade

- Certificar-se que a exclusão de parcerias ocorre conforme [protótipo](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0).
- Consumir rota para excluir parceria.

## Informações para execução da atividade

- Somente usuários administradores podem excluir parcerias, e deve manter um histórico

## DoR

- [x] Cabe em uma sprint (de preferência não maior que 8 story points)
- [x] Validado com o cliente
- [x] Prototipado

## DoD

- [x] Testado e integrado
- [x] Sem bugs observados / review
- [x] Code review
- [x] Atende aos critérios de aceite
- [x] Documentado
- [x] Aceito pelo PO

**Comment by MariaGabrielaReis** [comment]
# Documentação

Foi utilizado a classe criada para agrupar as requisições que envolvem as parcerias (PartnershipController), onde existe uma função para deletar parcerias. Esse delete foi feito consumindo a rota do backend através dessa função e, ao enviar o id, foi enviado ao servidor e recarregado a tela da parceria.


**Tecnologias:** React Native, Expo, Axios, Styled Components

https://user-images.githubusercontent.com/69374340/229389365-74d0b0f4-4990-43b4-91f6-d1623524fd75.mp4

### Requisição
```ts
 async deletePartnership(id: string) {
    try {
      await api.delete(PARTNERSHIP_ENDPOINTS.DELETE + id);
      Alert.alert(
        "Parceria excluída!",
        "Esta parceria ainda vai aparecer na listagem, mas ações como editar ou adicionar anotação foram bloqueadas!",
      );
    } catch (error) {
      console.error(error);
    }
  }
```

### Botão para deletar parceria
```ts
 <Button type="unfilled" onPress={handleDeletePartnership}>
     Deletar parceria
 </Button>
```

### Função para excluir parceria
```ts
 async function handleDeletePartnership() {
    await PartnershipController.deletePartnership(partnershipId);
    getData(); // função que recarrega os dados da parceria
  }
```

**Comment by gioliveirass** [comment]
Não foi feita a separação de parcerias ativas e deletadas?
